// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sf.Budgeteer.Infrastructure;

namespace Sf.Budgeteer.Infrastructure.Migrations
{
    [DbContext(typeof(BudgeteerContext))]
    [Migration("20181207205815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sf.Budgeteer.ApplicationCore.Entities.BudgetAggregate.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BudgetMonth");

                    b.Property<int>("BudgetYear");

                    b.HasKey("Id");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("Sf.Budgeteer.ApplicationCore.Entities.BudgetAggregate.BudgetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("AmountType");

                    b.Property<int?>("BudgetId");

                    b.Property<int?>("CategoryId");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BudgetItem");
                });

            modelBuilder.Entity("Sf.Budgeteer.ApplicationCore.Entities.BudgetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("BudgetCategory");
                });

            modelBuilder.Entity("Sf.Budgeteer.ApplicationCore.Entities.BudgetAggregate.BudgetItem", b =>
                {
                    b.HasOne("Sf.Budgeteer.ApplicationCore.Entities.BudgetAggregate.Budget", "Budget")
                        .WithMany("BudgetItems")
                        .HasForeignKey("BudgetId");

                    b.HasOne("Sf.Budgeteer.ApplicationCore.Entities.BudgetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
